services:
  postgres:
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lifepack_test

  api:
    build:
      target: dev
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/lifepack_test?schema=public
